sno=prompt("enter student number..:")
sname=prompt("enter student name..:")
sclass=prompt("enter student class..:")
ssec=prompt("enter student section..:")
m1=parseInt(prompt("Enter m1..:"))
m2=parseInt(prompt("Enter m2..:"))
m3=parseInt(prompt("Enter m3..:"))
m4=parseInt(prompt("Enter m4..:"))
m5=parseInt(prompt("Enter m5..:"))
m6=parseInt(prompt("Enter m6..:"))
tot=m1+m2+m3+m4+m5+m6
avg=tot/6
console.log("-------------")
console.log("MARKS REPORT")
console.log("-------------")
console.log("Sno=",sno,"","Sname=",sname)
console.log("Sclass=",sclass,"","Ssec=",ssec)
console.log("************")
console.log("M1=",m1,"","M2=",m2)
console.log("M3=",m3,"","M4=",m4)
console.log("M5=",m5,"","M6=",m6)
console.log("-------------")
console.log("-------------")
console.log("total marks=",tot)
console.log("average marks=",avg)
console.log("-------------")
